In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("used_bikes Task 2.csv")

df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   149 non-null    object
 1   price       149 non-null    float64
 2   city        149 non-null    object
 3   kms_driven  149 non-null    float64
 4   owner       149 non-null    object
 5   age         149 non-null    float64
 6   power       149 non-null    float64
 7   brand       149 non-null    object
dtypes: float64(4), object(4)
memory usage: 9.4+ KB

In [5]:
df.dtypes

bike_name      object
price         float64
city           object
kms_driven    float64
owner          object
age           float64
power         float64
brand          object
dtype: object

In [6]:
before = df.memory_usage(deep=True).sum() / 1024**2

print(f"Memory Usage Before Optimization: {before:.2f} MB")

Memory Usage Before Optimization: 0.04 MB

In [7]:
df.dtypes

bike_name      object
price         float64
city           object
kms_driven    float64
owner          object
age           float64
power         float64
brand          object
dtype: object

In [8]:
for col in df.select_dtypes(include=['int64']).columns:
    df[col] = pd.to_numeric(df[col], downcast='integer')

for col in df.select_dtypes(include=['float64']).columns:
    df[col] = pd.to_numeric(df[col], downcast='float')

for col in df.select_dtypes(include=['object']).columns:
    if df[col].nunique() / len(df) < 0.5:
        df[col] = df[col].astype('category')

In [9]:
after = df.memory_usage(deep=True).sum() / 1024**2

print(f"Memory Usage After Optimization: {after:.2f} MB")

Memory Usage After Optimization: 0.02 MB

In [10]:
print(f"Reduction: {before-after:.2f} MB")

Reduction: 0.02 MB

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   149 non-null    object
 1   price       149 non-null    float32
 2   city        149 non-null    category
 3   kms_driven  149 non-null    float32
 4   owner       149 non-null    category
 5   age         149 non-null    float32
 6   power       149 non-null    float32
 7   brand       149 non-null    category
dtypes: category(3), float32(4), object(1)
memory usage: 6.2+ KB

In [12]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 2.1 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [13]:
from sqlalchemy import create_engine

username = "root"
password = "root"
host = "localhost"
database = "bike_db"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}/{database}"
)

In [15]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:your_password@localhost:3306/bike_db"
)

In [ ]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP INDEX idx_brand ON used_bikes"))
    conn.commit()

In [ ]:
df.to_sql(
    "used_bikes",
    engine,
    if_exists="append",
    index=False
)

In [ ]:
with engine.connect() as conn:
    conn.execute(text("""
        CREATE INDEX idx_brand
        ON used_bikes(brand);
    """))
    conn.commit()

## Conclusion

- Successfully loaded the CSV file.
- Optimized the data types and reduced memory usage.
- Prepared the code to insert data into MySQL.
- Removed the existing index before insertion.
- Recreated the index after insertion.
- This process is suitable for daily ETL jobs.